//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class TestClassWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(TestClass), typeof(System.Object));
		L.RegFunction("TestFun", TestFun);
		L.RegFunction("New", _CreateTestClass);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateTestClass(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				TestClass obj = new TestClass();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: TestClass.New");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int TestFun(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			TestClass.TestFun();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

